org: higorhms
app: http-serverless
service: serverless-chatgpt
frameworkVersion: '3'

params:
  default:
    dbName: serverless-chatgpt
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGODB_CONNECTION_STRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}

functions:
  api:
    handler: api/index.handler
    events:
      - httpApi:
          path: /
          method: get
  send:
    handler: api/index.send
    events:
      - httpApi:
          path: /
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/get-answer-request.json)}

plugins:
  - serverless-offline