org: higorhms
app: http-serverless
service: serverless-chatgpt
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: api/index.handler
    events:
      - httpApi:
          path: /
          method: get
  send:
    handler: api/index.send
    events:
      - httpApi:
          path: /
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/get-answer-request.json)}

plugins:
  - serverless-offline